### ISSUE TITLE
Bringing this feature into core vim

### ISSUE THREAD

**Issue by bruno-** [ConradIrwin/vim-bracketed-paste#9]
Hi,
I really really like this feature! Thanks for spreading the word on reddit and making this plugin.

After thinking about this for a while, I thought: why wouldn't this feature be built into vim itself? So I just opened a discussion on vim_dev mailing list, here's the [link](https://groups.google.com/forum/?fromgroups#!topic/vim_dev/JmqZ_N_VBtw).
I've linked to your blog and to this plugin.

Maybe I should've contacted you before doing that, but I was too excited :)

Anyway, just wanted to let you know this. Feel free to close the issue.

**Comment by Firef0x** [comment]
Hello, @bruno- @ConradIrwin !

Any follow-up or latest news about this? The thread above just ends in Jul 15 2014 . :confounded: 

Yours sincerely!
